DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS access;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE access (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_started TIMESTAMP NOT NULL,
    access INTEGER NOT NULL
)