apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends
    spec:
      containers:
      - image: vertefra/techtrends:latest
        imagePullPolicy: Always      
        name: techtrends
        ports:
        - containerPort: 3111

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111

        resources:
          requests:
            cpu: 250m
            memory: 54Mi
          limits:
            cpu: 500m
            memory: 128Mi
status: {}
