name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: vertefra/techtrends
      TAG: latest
    steps:
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        run: |
          /app/scripts/build.sh && \
          /app/scripts/push.sh 
